### ISSUE TITLE
File > New Telerik Project templates

### ISSUE THREAD

**Issue by EdCharbeneau** [telerik/scaffold-templates-core#3]
We should be using the new themes in our templates for new projects. Especially ASP.NET Core 2.2 and higher since these default to Bootstrap 4 now. If we can make BS4 our baseline for 2.2+ we can take advantage of our v2 themes new `k-form` classes and ripple FX.

**Comment by Dimitar-Goshev** [comment]
@EdCharbeneau We have updated all our VS Extension project templates to use BS4, instead of BS3, and our SASS based Bootstrap v4 theme. They target R2 2019 release.
